openapi: 3.0.0
info:
  title: Appwrite API
  version: "0.9.3"
servers:
  - url: https://appwrite.io/v1
paths:
  /account:
    get:
      summary: Get Account Info
      responses:
        '200':
          description: Success
  /avatars/favicon:
    get:
      summary: Get Favicon
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
